[package]
name = "tofu-cli"
version = "0.1.0"
edition = "2024"
description = "A terminal-first webhook relay CLI for local development."
homepage = "https://trytofu.dev"
repository = "https://github.com/trytofu/tofu-cli"
license = "MIT"

[dependencies]
clap = { version = "4", features = ["derive"] }
futures-util = "0.3"
reqwest = { version = "0.13.4", features = ["json", "stream"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.150"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal"] }
toml = "1.1.2"
dirs = "6"
comfy-table = "7"
colored = "3.0.0"
thiserror = "2.0.18"
chrono = "0.4"

[[bin]]
name = "tofu"
path = "src/main.rs"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

[package.metadata.dist]
formula = "tofu"
